### ISSUE TITLE
ktx2 failed to checkout

### ISSUE THREAD

**Issue by lyd405121** [KhronosGroup/glTF-IBL-Sampler#17]
## git submodule update --init --recursive
Cloning into 'G:/linyaodong/glTF-IBL-Sampler/thirdparty/slimktx2'...
Host key verification failed.
fatal: Could not read from remote repository.
## Seems that ktx2 failed
![emmmm](https://user-images.githubusercontent.com/16344694/103336295-a94d9480-4ab2-11eb-954a-66721d335dac.png)

**Comment by emackey** [comment]
@UX3D-nopper Looks like glTF-IBL-Sampler, which is not archived, depends on submodule SlimKTX2, which is archived.

Is glTF-IBL-Sampler still active?

**Comment by UX3D-nopper** [comment]
Yes, and instead of SlimKTX2 libktx is used: 
https://github.com/KhronosGroup/glTF-IBL-Sampler/pull/16
@UX3D-becher and @UX3D-haertl Can you please accept and merge?

**Comment by UX3D-nopper** [comment]
libKTX is used, so closing.
